const DICT_TYPE_MODULE_TYPE = 'module_type'
const DICT_TYPE_MODULE_TYPE_PAGE = 'p'
const DICT_TYPE_MODULE_TYPE_MENU = 'm'
const DICT_TYPE_MODULE_TYPE_CONTENTS = 'c'
export default {
  DICT_TYPE_MODULE_TYPE,
  DICT_TYPE_MODULE_TYPE_PAGE,
  DICT_TYPE_MODULE_TYPE_MENU,
  DICT_TYPE_MODULE_TYPE_CONTENTS
}
